### ISSUE TITLE
5.0以上aapt打包后LayoutInflate报错，You must supply a layout_width attribute.

### ISSUE THREAD

**Issue by zjf1023** [bunnyblue/ACDD#25]
你好，我用提供的aapt打包apk后直接安装，5.0以上系统在inflate view的时候报错，5.0以下正常使用。
日志是：
Caused by: java.lang.RuntimeException: Binary XML file line #70: You must supply a layout_width attribute.
at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:619)
at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6786)
at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6955)
at android.widget.RelativeLayout$LayoutParams.<init>(RelativeLayout.java:1244)
at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:1084)
at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:83)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:820)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
at android.view.LayoutInflater.inflate(LayoutInflater.java:366)

我追查下了源码，5.0在TypedArray的getLayoutDimension方法中会
throw new UnsupportedOperationException(getPositionDescription()
                + ": You must supply a " + name + " attribute.");
请问遇到过这个问题么？  谢谢

**Comment by bunnyblue** [comment]
没遇到过，你的布局怎么写的

**Comment by zjf1023** [comment]
我明白了 是我的布局中有个style，  我看你gitHub中，这个style 在5.0以上要用0x7f开头的是么？
![Uploading image.png…]()

**Comment by bunnyblue** [comment]
5.0以上要theme要0x7f  androidfw的限制，这个没啥好办法，如果一定要用的话这个放在宿主里面，然后引用，直接引用有问题

**Comment by zjf1023** [comment]
好的，谢谢~

**Comment by zjf1023** [comment]
你好，我想再问下，这个style 在宿主中的话，只能打包成R文件用代码引么？  5.0以上手机，我想在xml文件中引入style和theme有什么好的方法么？ 就是style="@style/common_button_style" 这种形式

**Comment by bunnyblue** [comment]
在public定义style，然后在布局直接引用
