### ISSUE TITLE
android 2.3系统不支持

### ISSUE THREAD

**Issue by wenchl** [bunnyblue/ACDD#39]
你好，目前acdd针对于2.3系统会出现无法加载的情况。请问你们何时能支持2.3？

**Comment by bunnyblue** [comment]
无法加载描述下，6.0支持，贴上堆栈，描述下怎么出现的

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by wenchl** [comment]
那你们最低现在支持到哪个版本？

**Comment by bunnyblue** [comment]
api 14+

**Comment by wenchl** [comment]
会有下面这个错，先给你们记录一下吧。
 HackAssertionException
                                                     org.acdd.hack.Hack$HackDeclaration$HackAssertionException: java.lang.NoSuchMethodException: currentProcessName;android.app.ActivityThread->currentProcessName;@@@@
                                                         at org.acdd.hack.a.onAssertionFailure(ACDDHacks.java:339)
                                                         at org.acdd.hack.Hack.b(Hack.java:315)
                                                         at org.acdd.hack.Hack.a(Hack.java:39)
                                                         at org.acdd.hack.Hack$d.<init>(Hack.java:288)
                                                         at org.acdd.hack.Hack$a.a(Hack.java:114)
                                                         at org.acdd.hack.a.d(ACDDHacks.java:307)
                                                         at org.acdd.hack.a.a(ACDDHacks.java:196)
                                                         at org.acdd.framework.a.a(ACDD.java:106)
                                                         at org.acdd.android.a.a.a(ACDDInitializer.java:81)
                                                         at org.acdd.android.compat.ACDDApp.d(ACDDApp.java:105)
                                                         at org.acdd.android.compat.ACDDApp.attachBaseContext(ACDDApp.java:78)
                                                         at android.app.Application.attach(Application.java:77)
                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:958)
                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:942)
                                                         at android.app.LoadedApk.makeApplication(LoadedApk.java:461)
                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3280)
                                                         at android.app.ActivityThread.access$2200(ActivityThread.java:117)
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:969)
                                                         at android.os.Handler.dispatchMessage(Handler.java:99)
                                                         at android.os.Looper.loop(Looper.java:130)
                                                         at android.app.ActivityThread.main(ActivityThread.java:3703)
                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                         at java.lang.reflect.Method.invoke(Method.java:507)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
                                                         at dalvik.system.NativeStart.main(Native Method)

**Comment by wenchl** [comment]
Could not init ACDD framework !!!
                                                                   java.lang.NoClassDefFoundError: android.app.Fragment
                                                                       at org.acdd.runtime.InstrumentationHook.<init>(InstrumentationHook.java:283)
                                                                       at org.acdd.framework.a.a(ACDD.java:114)
                                                                       at org.acdd.android.a.a.a(ACDDInitializer.java:81)
                                                                       at org.acdd.android.compat.ACDDApp.d(ACDDApp.java:105)
                                                                       at org.acdd.android.compat.ACDDApp.attachBaseContext(ACDDApp.java:78)
                                                                       at android.app.Application.attach(Application.java:77)
                                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:958)
                                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:942)
                                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:461)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3280)
                                                                       at android.app.ActivityThread.access$2200(ActivityThread.java:117)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:969)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                       at android.os.Looper.loop(Looper.java:130)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:3703)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:507)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by bunnyblue** [comment]
正在解决

**Comment by bunnyblue** [comment]
fix at https://github.com/bunnyblue/ACDD/releases/tag/V1.4.0
