### ISSUE TITLE
Resources$NotFoundException

### ISSUE THREAD

**Issue by ljz2009y** [bunnyblue/ACDD#4]
我采用LZ的编译要求编译，不知道为什么还是以出现这个错误。。。

Log：

09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0300b3
09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ at android.content.res.Resources.getValue(Resources.java:1046)
09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ at android.content.res.MiuiResources.getValue(MiuiResources.java:139)
09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ at android.content.res.Resources.loadXmlResourceParser(Resources.java:2144)
09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ at android.content.res.Resources.getLayout(Resources.java:885)
09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ at android.view.LayoutInflater.inflate(LayoutInflater.java:464)
09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ at android.view.LayoutInflater.inflate(LayoutInflater.java:417)
09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:334)
09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ at android.app.Activity.setContentView(Activity.java:1944)
09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ at com.wlqq.android.activity.DriverSplashActivity.onCreate(DriverSplashActivity.java:72)
09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ at android.app.Activity.performCreate(Activity.java:5086)
09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ at com.openatlas.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:503)
09-20 12:36:09.883  27177-27177/com.openatlas.launcher W/System.err﹕ ... 13 more

**Comment by ljz2009y** [comment]
剩余的Log：
0 12:36:09.893  27177-27177/com.openatlas.launcher E/AndroidHack﹕ java.lang.RuntimeException: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.openatlas.launcher/com.wlqq.android.activity.DriverSplashActivity}: java.lang.RuntimeException: (3)ContextThemeWrapper_mResources is null paths in runtime:newDelegateResources [/data/app/com.openatlas.launcher-1.apk,/data/data/com.openatlas.launcher/lib/libcom_openatlas_android_game2.so,/data/data/com.openatlas.launcher/lib/libcom_openatlas_homelauncher.so,/data/data/com.openatlas.launcher/lib/libcom_openatlas_qrcode.so,/data/data/com.openatlas.launcher/lib/libcom_openatlas_universalimageloader_sample.so,/data/data/com.openatlas.launcher/lib/libcom_wlqq.so,]
            at com.openatlas.hack.AndroidHack$HandlerHack.handleMessage(AndroidHack.java:98)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4914)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:808)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:575)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.openatlas.launcher/com.wlqq.android.activity.DriverSplashActivity}: java.lang.RuntimeException: (3)ContextThemeWrapper_mResources is null paths in runtime:newDelegateResources [/data/app/com.openatlas.launcher-1.apk,/data/data/com.openatlas.launcher/lib/libcom_openatlas_android_game2.so,/data/data/com.openatlas.launcher/lib/libcom_openatlas_homelauncher.so,/data/data/com.openatlas.launcher/lib/libcom_openatlas_qrcode.so,/data/data/com.openatlas.launcher/lib/libcom_openatlas_universalimageloader_sample.so,/data/data/com.openatlas.launcher/lib/libcom_wlqq.so,]
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2092)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
            at android.app.ActivityThread.access$600(ActivityThread.java:140)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
            at com.openatlas.hack.AndroidHack$HandlerHack.handleMessage(AndroidHack.java:68)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4914)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:808)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:575)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: (3)ContextThemeWrapper_mResources is null paths in runtime:newDelegateResources [/data/app/com.openatlas.launcher-1.apk,/data/data/com.openatlas.launcher/lib/libcom_openatlas_android_game2.so,/data/data/com.openatlas.launcher/lib/libcom_openatlas_homelauncher.so,/data/data/com.openatlas.launcher/lib/libcom_openatlas_qrcode.so,/data/data/com.openatlas.launcher/lib/libcom_openatlas_universalimageloader_sample.so,/data/data/com.openatlas.launcher/lib/libcom_wlqq.so,]
            at com.openatlas.runtime.InstrumentationHook.HandleResourceNotFound(InstrumentationHook.java:283)
            at com.openatlas.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:510)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2056)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
            at android.app.ActivityThread.access$600(ActivityThread.java:140)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
            at com.openatlas.hack.AndroidHack$HandlerHack.handleMessage(AndroidHack.java:68)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4914)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:808)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:575)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by bunnyblue** [comment]
插件的id不能是0x7f  aapt dump resources  pkg|grep Package 看下

**Comment by ljz2009y** [comment]
你好，但是我的项目中：
AndroidManifest.xml和build.gradle中，都是写的：3.9.50x7e

并不是0x7f

**Comment by ljz2009y** [comment]
另外麻烦LZ能写一个插件apk生成的教程嘛，感觉博客和源码不是特别好懂。

**Comment by bunnyblue** [comment]
你自己看下你生成的apk吧

**Comment by ljz2009y** [comment]
我看了我生成的apk确实是0x7f，我只是很好奇，如何使用你的aapt去build apk来达到插件化。

**Comment by bunnyblue** [comment]
https://github.com/bunnyblue/ACDDExtension/tree/master/buildTools/binary/build.tool.R22 用这个
