### ISSUE TITLE
stubModeEnable开启demo运行报错

### ISSUE THREAD

**Issue by yangyonguo** [bunnyblue/ACDD#55]
我将demo中插件com.acdd.android.appcenter在宿主清单文件里的声明注释掉，然后点击菜单“startUninstalled”报错（错误信息见下面），请问是不是stubModeEnable开启的话，插件只能使用AUTO启动方式？

错误日志：
```Java
03-24 14:16:20.833 5238-5238/org.acdd.launcher I/BundleLifecycleHandler: Bundle installation info com.acdd.android.appcenter:[com.acdd.android.appcenter.download.GcAppDownLoadService, com.acdd.android.appcenter.AppProvider, com.acdd.android.appcenter.GameStaticReceiver, com.acdd.android.appcenter.main.ActivityInternalActivity, com.acdd.android.appcenter.main.GcContainerActivity]
03-24 14:16:20.834 5238-5238/org.acdd.launcher I/BundleLifecycleHandler: loaded() spend 5 milliseconds
03-24 14:16:20.834 5238-5238/org.acdd.launcher D/BundleLifecycleHandler: installed com.acdd.android.appcenter
03-24 14:16:20.834 5238-5238/org.acdd.launcher I/BundleImpl: Framework: Bundle com.acdd.android.appcenter loaded. 9 ms
03-24 14:16:20.838 5238-5238/org.acdd.launcher W/System.err: java.lang.reflect.InvocationTargetException
03-24 14:16:20.846 5238-5238/org.acdd.launcher W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-24 14:16:20.846 5238-5238/org.acdd.launcher W/System.err:     at org.acdd.hack.Hack$HackedMethod.invoke(Hack.java:260)
03-24 14:16:20.846 5238-5238/org.acdd.launcher W/System.err:     at org.acdd.runtime.InstrumentationHook$ExecStartActivityCallbackImpl_JELLY_BEAN.execStartActivity(InstrumentationHook.java:162)
03-24 14:16:20.846 5238-5238/org.acdd.launcher W/System.err:     at org.acdd.runtime.InstrumentationHook.execStartActivityInternal(InstrumentationHook.java:381)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at org.acdd.runtime.InstrumentationHook.execStartActivity(InstrumentationHook.java:322)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:4030)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:3984)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at android.app.Activity.startActivity(Activity.java:4314)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at android.app.Activity.startActivity(Activity.java:4282)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at com.acdd.homelauncher.MainActivity.onOptionsItemSelected(MainActivity.java:95)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at android.app.Activity.onMenuItemSelected(Activity.java:3008)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:353)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1189)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:234)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at android.widget.AdapterView.performItemClick(AdapterView.java:314)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at android.widget.AbsListView.performItemClick(AbsListView.java:1155)
03-24 14:16:20.847 5238-5238/org.acdd.launcher W/System.err:     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3068)
03-24 14:16:20.848 5238-5238/org.acdd.launcher W/System.err:     at android.widget.AbsListView$3.run(AbsListView.java:3933)
03-24 14:16:20.848 5238-5238/org.acdd.launcher W/System.err:     at android.os.Handler.handleCallback(Handler.java:743)
03-24 14:16:20.848 5238-5238/org.acdd.launcher W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-24 14:16:20.848 5238-5238/org.acdd.launcher W/System.err:     at android.os.Looper.loop(Looper.java:150)
03-24 14:16:20.848 5238-5238/org.acdd.launcher W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5546)
03-24 14:16:20.848 5238-5238/org.acdd.launcher W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-24 14:16:20.848 5238-5238/org.acdd.launcher W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
03-24 14:16:20.848 5238-5238/org.acdd.launcher W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
03-24 14:16:20.848 5238-5238/org.acdd.launcher W/System.err: Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {org.acdd.launcher/com.acdd.android.appcenter.main.GcContainerActivity}; have you declared this activity in your AndroidManifest.xml?
03-24 14:16:20.849 5238-5238/org.acdd.launcher W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
03-24 14:16:20.849 5238-5238/org.acdd.launcher W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
03-24 14:16:20.849 5238-5238/org.acdd.launcher W/System.err: 	... 30 more
```

**Comment by bunnyblue** [comment]
AUTO DELAY STORE三种模式

描述下具体机器。还有就是版本

**Comment by yangyonguo** [comment]
运行环境：
HUAWEI PE-TL10  Android6.0

ACDD版本:
commit c2a6377910c406e07afd4e896f8e1036c17b1495

**Comment by bunnyblue** [comment]
这个用于免注册启动Activity

**Comment by yangyonguo** [comment]
“这个用于免注册启动Activity”，我这智商有点捉急，麻烦能详细说一下吗？谢谢！

**Comment by bunnyblue** [comment]
插件的组件需要在宿主注册，具体你可以看下wiki，里面说的比较详细了。
比如说A中有个B，B需要在宿主注册，不然回报找不到未声明的异常。

后来添加了Activity和Receiver免注册，也就是stubmode，当初考虑到各种原因，默认关关闭了（这个我不确定有没有人用了，很少有反馈这个的），还是倾向于在宿主注册，因为Provider的的特性，没做Provider的支持，Service也是，App还是应该性能优先。

**Comment by yangyonguo** [comment]
恩，WIKI里我看到了是需要在宿主里注册所有插件里的组件。
只是，后来我想到一种应用场景：如果插件的组件不需要再宿主注册，就可以让插件动态升级，否则如果插件增加新组件，宿主应用也得升级。不知道stub mode是否就是出于解决这个问题的目的而设计的？

**Comment by bunnyblue** [comment]
第二次启动是不是就不报异常了？

**Comment by yangyonguo** [comment]
刚测试了一下，是这样的，第二次启动就可以了

**Comment by bunnyblue** [comment]
```
对于组件之间有依赖关系的话，可以这样声明
   <meta-data android:name="dependency" android:value="com.acdd.homelauncher"/>
这样子的话组件启动的会首先处理依赖问题，如果有多个的话可以逗号隔开
```
不过这样子的话组件会启动实际上你可能用不到
也可以参照[view](https://github.com/bunnyblue/ACDDExtension/blob/278c1a87aa6dd25541a62002fa43bc549fbee3db/Samples/HomeLauncher/src/main/java/com/acdd/homelauncher/MainActivity.java)

```
ACDD.getInstance().checkBundleInstall("com.acdd.android.appcenter");
```
来确保bundle成功加载

**Comment by bunnyblue** [comment]
ref [wiki](https://github.com/bunnyblue/ACDD/wiki/AboutStubMode_CN)

**Comment by huzgHost** [comment]
Activity,Service都可以正常调用，Broadcast怎么就收不到广播呢？

**Comment by bunnyblue** [comment]
@huzgHost  具体描述下

**Comment by huzgHost** [comment]
@bunnyblue  是我的问题，解决了。 InstrumentationHook 这个类起到什么作用？可以讲讲么

**Comment by bunnyblue** [comment]
拦截Instrumentation 处理Activity的启动等等，Instrumentation具体的资料你可以看源码
```
/**
 * Base class for implementing application instrumentation code.  When running
 * with instrumentation turned on, this class will be instantiated for you
 * before any of the application code, allowing you to monitor all of the
 * interaction the system has with the application.  An Instrumentation
 * implementation is described to the system through an AndroidManifest.xml's
 * &lt;instrumentation&gt; tag.
 */
```

**Comment by huzgHost** [comment]
@bunnyblue   你好，我想咨询一下，如果是一个新的so,一开始并未加入，而是通过放入sd卡目录下，通过ACDD.getInstance().installBundle()来安装的话，会因为mBundleInfoList中未存在这个新的so的名称而出错？

**Comment by bunnyblue** [comment]
mBundleInfoList 这边可以把东西加进去，暂时没做。最近忙得不可开交。你改下自己放进去吧

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by huzgHost** [comment]
@bunnyblue   嗯，看到了这个问题，是想确认一下。   Thank you!
